// Parity of `configHash` with the real, pinned `perch-doc-compiler` contract.
//
// Nothing previously checked that `configHash`'s
// `configHashOfCanonical(canonicalJson(recovery))` path (perch-js's
// canonicalizer plus this SDK's own sha256) produces the same `config_hash`
// the real compiler returns for the same document — a drift here would
// silently misdirect every Protected reconfiguration approval even though
// the statement-vector tests stay green (Copilot's finding on
// nidohq/nido#232, doc.ts:147).
//
// `config-hash-vectors.local.json` is generated by
// `crates/integration-tests/tests/it/config_hash_vectors.rs`
// (`cargo test -p nido-integration-tests --test it config_hash_vectors`),
// which builds real documents and reads the real compiler's own
// `config_hash` for each. This is a local, regeneratable fixture, not a
// committed one yet.

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { configHash } from './doc.js';
import type { PolicyDoc } from '@stellar-registry/perch';

interface Vector {
  label: string;
  recovery: unknown;
  config_hash: string;
}

const fixturePath = new URL('./testdata/config-hash-vectors.local.json', import.meta.url);
const vectors: Vector[] = JSON.parse(readFileSync(fixturePath, 'utf8'));

describe('configHash parity with the real perch-doc-compiler', () => {
  it('has vectors to check', () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    it(`matches the compiler for ${v.label}`, () => {
      const doc = { recovery: v.recovery } as unknown as PolicyDoc;
      const hash = configHash(doc);
      expect(hash).toBeDefined();
      expect(Buffer.from(hash!).toString('hex')).toBe(v.config_hash);
    });
  }
});
