import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { p2 } from './poseidon.js';
import { DOM_AUTH, DOM_NULL } from './field.js';
import { wrapLeafInner, wrapLeafStored, computeNullifier, computeAuthHash } from './authHash.js';

// Parity gate: `computeAuthHash`/`computeNullifier`/leaf-wrap MUST byte-match
// the on-chain controller recompute (`contracts/zk-recovery/src/hash.rs`) --
// a mismatch here means every real proof's public input fails to verify.
// Fixture copied verbatim from `hash.rs`'s `#[cfg(test)] mod tests` (the M1
// lifecycle fixture), which in turn is asserted equal to the circuit-committed
// `circuits/zk_recovery/fixtures/lifecycle/prover_inputs.json`.
const vectorsPath = fileURLToPath(
  new URL('../../../../tests/vectors/zk-recovery/vectors.json', import.meta.url),
);
const vectors = JSON.parse(readFileSync(vectorsPath, 'utf8'));
const circuit = vectors.circuit as {
  secret: string;
  acct_hi: string;
  acct_lo: string;
  action: string;
  npass_hi: string;
  npass_lo: string;
  ctrl_hi: string;
  ctrl_lo: string;
  pk_prefix: string;
  pk_x_hi: string;
  pk_x_lo: string;
  pk_y_hi: string;
  pk_y_lo: string;
  nonce: string;
  timelock_secs: string;
  nullifier: string;
  auth_hash: string;
};

function hexToBytes(hex: string, expectedLen: number): Uint8Array {
  const s = hex.startsWith('0x') ? hex.slice(2) : hex;
  if (s.length !== expectedLen * 2) {
    throw new Error(`hexToBytes: expected ${expectedLen} bytes, got ${s.length / 2}`);
  }
  const out = new Uint8Array(expectedLen);
  for (let i = 0; i < expectedLen; i++) {
    out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

describe('hash.rs M1 lifecycle fixture (contract parity, HARD STOP on mismatch)', () => {
  const ACCOUNT = new Uint8Array(32).fill(0x11);
  const CONTROLLER = new Uint8Array(32).fill(0x22);
  const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
  const ACTION = 1 as const;
  const NONCE = 1n;
  const TIMELOCK_SECS = 1_209_600;
  const SECRET = BigInt(
    '0x00000000000000000000000000000000d80e5c7596cf3ed7868f8bc89b6cf93c',
  );
  const NEW_PUBKEY = hexToBytes(
    '0x042bb2f07c58a9bacf9e794ba2b1589292716ca4b05a6d97b97eb293a160898b00f9fa128ee95baeceff2a25348632424406106595b3dd673db63bb3eef0815186',
    65,
  );
  const LEAF_STORED = BigInt(
    '0x27cfe62058beb8e80b7c27b5b43225643b3b062f300c3bd28f41ddd20de50880',
  );
  const NULLIFIER = BigInt(
    '0x1b2c4afb313af3435729561fee62d1b065c4b3aad8e8fc6ca5447936a2f8edce',
  );
  const AUTH_HASH = BigInt(
    '0x111ae1edc6e6854540153d3098793786fe1f37bd208992a95b9d9038d9c37baf',
  );

  it('wrapLeafStored(account, wrapLeafInner(secret)) equals LEAF_STORED_HEX', () => {
    const inner = wrapLeafInner(SECRET);
    expect(wrapLeafStored(ACCOUNT, inner)).toBe(LEAF_STORED);
  });

  it('computeNullifier(account, secret) equals NULLIFIER_HEX', () => {
    expect(computeNullifier(ACCOUNT, SECRET)).toBe(NULLIFIER);
  });

  it('computeAuthHash(...) equals AUTH_HASH_HEX', () => {
    const got = computeAuthHash({
      action: ACTION,
      accountId32: ACCOUNT,
      networkPassphrase: NETWORK_PASSPHRASE,
      controllerId32: CONTROLLER,
      newPubkey65: NEW_PUBKEY,
      nonce: NONCE,
      timelockSecs: TIMELOCK_SECS,
    });
    expect(got).toBe(AUTH_HASH);
  });

  it('computeAuthHash for action 2/3 with newPubkey65=null zeroes pk_prefix/x/y (does not throw, differs from action-1 hash)', () => {
    const cancel = computeAuthHash({
      action: 2,
      accountId32: ACCOUNT,
      networkPassphrase: NETWORK_PASSPHRASE,
      controllerId32: CONTROLLER,
      newPubkey65: null,
      nonce: NONCE,
      timelockSecs: TIMELOCK_SECS,
    });
    const revoke = computeAuthHash({
      action: 3,
      accountId32: ACCOUNT,
      networkPassphrase: NETWORK_PASSPHRASE,
      controllerId32: CONTROLLER,
      newPubkey65: null,
      nonce: NONCE,
      timelockSecs: TIMELOCK_SECS,
    });
    expect(cancel).not.toBe(AUTH_HASH);
    expect(revoke).not.toBe(AUTH_HASH);
    expect(cancel).not.toBe(revoke);
  });
});

describe('vectors.circuit.nullifier/auth_hash (independent nargo-generated fixture)', () => {
  // These fields are synthetic small values (not derived from a real account
  // StrKey or sha256(networkPassphrase) preimage), so they're asserted here
  // via direct `p2` calls with the exact field order `computeAuthHash`/
  // `computeNullifier` use internally, rather than through the string/byte
  // -array public API -- an independent, order-sensitive cross-check of the
  // P2_4/P2_15 field ordering against a fixture generated by
  // `nargo test --show-output` (a different toolchain path than `hash.rs`'s
  // `cargo test`).
  it('P2_4(DOM_NULL, acct_hi, acct_lo, secret) equals vectors.circuit.nullifier', () => {
    const got = p2([DOM_NULL, BigInt(circuit.acct_hi), BigInt(circuit.acct_lo), BigInt(circuit.secret)]);
    expect(got).toBe(BigInt(circuit.nullifier));
  });

  it('P2_15(DOM_AUTH, ...) in the exact field order equals vectors.circuit.auth_hash', () => {
    const got = p2([
      DOM_AUTH,
      BigInt(circuit.action),
      BigInt(circuit.acct_hi),
      BigInt(circuit.acct_lo),
      BigInt(circuit.npass_hi),
      BigInt(circuit.npass_lo),
      BigInt(circuit.ctrl_hi),
      BigInt(circuit.ctrl_lo),
      BigInt(circuit.pk_prefix),
      BigInt(circuit.pk_x_hi),
      BigInt(circuit.pk_x_lo),
      BigInt(circuit.pk_y_hi),
      BigInt(circuit.pk_y_lo),
      BigInt(circuit.nonce),
      BigInt(circuit.timelock_secs),
    ]);
    expect(got).toBe(BigInt(circuit.auth_hash));
  });
});
