import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DEPTH, ZEROS, computeRoot, IncrementalTree } from './merkle.js';
import { wrapLeafInner, wrapLeafStored } from './authHash.js';

// Parity gate: `ZEROS` and the incremental tree's root computation must
// reproduce, byte-for-byte, the depth-24 zero-hash chain and single-leaf
// membership witness `circuits/zk_recovery` commits in
// `tests/vectors/zk-recovery/vectors.json` -- generated by
// `nargo test --show-output` on `src/tests.nr::single_leaf_membership_succeeds`
// (see the vector's `_comment`). A mismatch here means a real membership
// proof's `root` public input will never match what this SDK (or the pool
// contract's `merkle.rs`) computes.
const vectorsPath = fileURLToPath(
  new URL('../../../../tests/vectors/zk-recovery/vectors.json', import.meta.url),
);
const vectors = JSON.parse(readFileSync(vectorsPath, 'utf8'));
const circuit = vectors.circuit as {
  depth: number;
  secret: string;
  acct_hi: string;
  acct_lo: string;
  path_bits_all_zero: boolean;
  path_siblings_zero_hash_chain: string[];
  root: string;
};

/**
 * Reconstructs a 32-byte accountId32 whose `split16` halves equal the
 * vector's `acct_hi`/`acct_lo` (the vector gives those halves directly as
 * small field values rather than a real contract-id, since the circuit
 * fixture is synthetic -- this just inverts `split16`'s zero-extended-16-byte
 * convention so `wrapLeafStored` can be exercised with the vector's exact
 * field values).
 */
function accountId32FromHiLo(hiHex: string, loHex: string): Uint8Array {
  const halfBytes = (x: bigint): Uint8Array => {
    const out = new Uint8Array(16);
    let v = x;
    for (let i = 15; i >= 0; i--) {
      out[i] = Number(v & 0xffn);
      v >>= 8n;
    }
    return out;
  };
  const out = new Uint8Array(32);
  out.set(halfBytes(BigInt(hiHex)), 0);
  out.set(halfBytes(BigInt(loHex)), 16);
  return out;
}

describe('ZEROS matches the circuit zero-hash chain', () => {
  it('has length DEPTH + 1, with ZEROS[24] the empty-tree root', () => {
    expect(DEPTH).toBe(24);
    expect(ZEROS).toHaveLength(25);
  });

  it('ZEROS[0..24] equals vectors.circuit.path_siblings_zero_hash_chain', () => {
    const expected = circuit.path_siblings_zero_hash_chain.map((hex) => BigInt(hex));
    expect(expected).toHaveLength(DEPTH);
    for (let i = 0; i < DEPTH; i++) {
      expect(ZEROS[i]).toBe(expected[i]);
    }
  });
});

describe('single-leaf membership matches vectors.circuit', () => {
  const accountId32 = accountId32FromHiLo(circuit.acct_hi, circuit.acct_lo);
  const inner = wrapLeafInner(BigInt(circuit.secret));
  const leaf = wrapLeafStored(accountId32, inner);

  it('path_bits_all_zero holds for the vector (sanity on the fixture itself)', () => {
    expect(circuit.path_bits_all_zero).toBe(true);
  });

  it('IncrementalTree.insert(leaf) at index 0 then root() equals vectors.circuit.root', () => {
    const tree = new IncrementalTree();
    const index = tree.insert(leaf);
    expect(index).toBe(0);
    expect(tree.root()).toBe(BigInt(circuit.root));
  });

  it('computeRoot(leaf, 0, ZEROS[0..24]) equals vectors.circuit.root', () => {
    const root = computeRoot(leaf, 0, ZEROS.slice(0, DEPTH));
    expect(root).toBe(BigInt(circuit.root));
  });

  it('pathFor(0) on a single-leaf tree returns the zero-hash chain siblings and all-zero bits', () => {
    const tree = new IncrementalTree();
    tree.insert(leaf);
    const { siblings, bits } = tree.pathFor(0);
    expect(bits).toEqual(new Array(DEPTH).fill(0));
    expect(siblings).toHaveLength(DEPTH);
    for (let i = 0; i < DEPTH; i++) {
      expect(siblings[i]).toBe(ZEROS[i]);
    }
  });
});

describe('IncrementalTree with multiple leaves', () => {
  it('assigns sequential indices and pathFor reproduces the tree root via computeRoot', () => {
    const tree = new IncrementalTree();
    const leaves = [11n, 22n, 33n, 44n, 55n].map((secret) =>
      wrapLeafStored(new Uint8Array(32).fill(0x7), wrapLeafInner(secret)),
    );
    const indices = leaves.map((leaf) => tree.insert(leaf));
    expect(indices).toEqual([0, 1, 2, 3, 4]);

    const root = tree.root();
    for (let i = 0; i < leaves.length; i++) {
      const { siblings, bits } = tree.pathFor(i);
      expect(computeRoot(leaves[i], i, siblings)).toBe(root);
      // bits[level] must equal (i >> level) & 1
      for (let level = 0; level < DEPTH; level++) {
        expect(bits[level]).toBe((i >> level) & 1);
      }
    }
  });
});
