//! Pinned Stage 3 ZK-recovery fixture
//! (`firstmate/data/perch-zk-recovery-scout-p5/follow-up.md` §8;
//! `circuits/zk_recovery_doc`).
//!
//! Mirrors `crate::zk_fixture`'s pattern exactly (same account/controller
//! pins, same Merkle secret/leaf/root/nullifier — the field-swap only
//! changed what `auth_hash` binds, not the Merkle/nullifier witness), but
//! for the NEW doc-hash-binding circuit: the target document hash, config
//! version, and baseline are SYNTHETIC values (`[0x99; 32]`, `1`, `[0x88;
//! 32]`) — no real Perch document backs `target_doc_hash` (finding a real
//! document whose sha256 equals a specific pre-committed 32-byte value is
//! computationally infeasible, i.e. a hash preimage). Tests using this
//! fixture therefore validate ZK evidence verification through PROMOTION
//! (`submit_zk_proof` -> `AuthorizedPending`), not completion via a real
//! `apply_doc` call — `Policy::enforce`'s completion gate is mode-independent
//! shared code already proven end-to-end by the guardian-only integration
//! tests (`recovery_stage3_guardian_only.rs`), so re-proving it per mode
//! would not add coverage of anything mode-specific.
//!
//! Generated by `circuits/zk_recovery_doc/Prover.toml` + a real `bb prove`
//! run — see that file's own doc comment for full provenance and the exact
//! witness values.

use soroban_sdk::Env;

/// Identical to `zk_fixture::ACCOUNT` — this fixture's Merkle
/// secret/leaf/root/nullifier are the SAME witness as the M1 lifecycle
/// fixture (unaffected by the `auth_hash` field-list change).
pub const ACCOUNT: [u8; 32] = [0x11; 32];
pub const CONTROLLER: [u8; 32] = [0x22; 32];
pub const NETWORK_PASSPHRASE: &str = "Test SDF Network ; September 2015";
pub const NONCE: u64 = 1;
pub const TIMELOCK_SECS: u32 = 1_209_600;
pub const ACTION_LOST_KEY: u32 = 1;

/// Synthetic target document hash — see the module doc comment.
pub const TARGET_DOC_HASH: [u8; 32] = [0x99; 32];
pub const CFG_VERSION: u32 = 1;
/// Synthetic baseline/source commitment.
pub const BASELINE: [u8; 32] = [0x88; 32];

pub struct ZkRecoveryDocFixture {
    pub account: [u8; 32],
    pub controller: [u8; 32],
    pub network_passphrase: &'static str,
    pub nonce: u64,
    pub timelock_secs: u32,
    pub secret_hex: &'static str,
    pub leaf_stored: [u8; 32],
    pub root: [u8; 32],
    pub nullifier: [u8; 32],
    pub auth_hash: [u8; 32],
    pub proof: std::vec::Vec<u8>,
    pub public_inputs: std::vec::Vec<u8>,
}

const PROOF_BYTES: &[u8] = include_bytes!("../fixtures/zk_recovery_doc/proof");
const PUBLIC_INPUTS_BYTES: &[u8] = include_bytes!("../fixtures/zk_recovery_doc/public_inputs");

// Copied from `circuits/zk_recovery_doc/Prover.toml` (see that file for
// provenance) — IDENTICAL leaf/root/nullifier to the M1 lifecycle fixture's
// witness (`crate::zk_fixture::{LEAF_STORED_HEX,ROOT_HEX,NULLIFIER_HEX,SECRET_HEX}`,
// module-private there), duplicated here so this module has no dependency on
// that one beyond `SECRET_LABEL`.
const SECRET_HEX: &str = "0x00000000000000000000000000000000d80e5c7596cf3ed7868f8bc89b6cf93c";
const LEAF_STORED_HEX: &str = "0x27cfe62058beb8e80b7c27b5b43225643b3b062f300c3bd28f41ddd20de50880";
const ROOT_HEX: &str = "0x2d7fe2d38d95d1fcff89a94652adc57d0414cee707c72c0f744389025a937f03";
const NULLIFIER_HEX: &str = "0x1b2c4afb313af3435729561fee62d1b065c4b3aad8e8fc6ca5447936a2f8edce";
const AUTH_HASH_HEX: &str = "0x0f824a503a04acffc6ec611ef89dbb6a31fbd92a163864eff602e6d71905cb38";

fn hex32(s: &str) -> [u8; 32] {
    let s = s.strip_prefix("0x").unwrap_or(s);
    assert_eq!(s.len(), 64, "expected 32-byte hex string, got {s:?}");
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

/// Loads the pinned fixture: witness constants plus the real `bb prove`
/// `proof`/`public_inputs` generated for them.
///
/// # Panics
///
/// Panics if the committed fixture files have drifted out of sync with the
/// hardcoded hex constants here (`public_inputs` must equal `root ||
/// nullifier || auth_hash`) — regenerate via the `circuits/zk_recovery_doc`
/// build if this ever fires.
#[allow(unused_variables)]
#[must_use]
pub fn fixture(env: &Env) -> ZkRecoveryDocFixture {
    let root = hex32(ROOT_HEX);
    let nullifier = hex32(NULLIFIER_HEX);
    let auth_hash = hex32(AUTH_HASH_HEX);

    assert_eq!(
        PUBLIC_INPUTS_BYTES.len(),
        96,
        "public_inputs fixture must be 96 bytes"
    );
    assert_eq!(
        &PUBLIC_INPUTS_BYTES[0..32],
        &root[..],
        "public_inputs[0..32] must equal root"
    );
    assert_eq!(
        &PUBLIC_INPUTS_BYTES[32..64],
        &nullifier[..],
        "public_inputs[32..64] must equal nullifier"
    );
    assert_eq!(
        &PUBLIC_INPUTS_BYTES[64..96],
        &auth_hash[..],
        "public_inputs[64..96] must equal auth_hash"
    );

    ZkRecoveryDocFixture {
        account: ACCOUNT,
        controller: CONTROLLER,
        network_passphrase: NETWORK_PASSPHRASE,
        nonce: NONCE,
        timelock_secs: TIMELOCK_SECS,
        secret_hex: SECRET_HEX,
        leaf_stored: hex32(LEAF_STORED_HEX),
        root,
        nullifier,
        auth_hash,
        proof: PROOF_BYTES.to_vec(),
        public_inputs: PUBLIC_INPUTS_BYTES.to_vec(),
    }
}
